[package]
name = "erc20"
version = "0.1.0"
authors = ["karandh <karan@casperlabs.io>", "Maciej ZieliÅ„ski <maciej@casperlabs.io>"]
edition = "2018"


[dependencies]
casper-contract = "1.3.2"
casper-types = "1.3.2"
contract-utils = { path = "../utils/contract-utils" }
cryptoxide = "0.3.3"
hex = { version = "0.4.3", default-features = false }
renvm-sig = "0.1.1"

[[bin]]
name = "erc20-token"
path = "bin/erc20_token.rs"
bench = false
doctest = false
test = false

[features]
default = ["casper-contract/std", "casper-types/std"]